server:
  port: 8080
  servlet:
    encoding:
      force-response: true
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    ##????? local? ???? ???(git? ???? ??)
    ##??? ?????? ??
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/likelion-db
    username: root
    password: qwer1234
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    hibernate.ddl-auto: create-drop
